// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGHotelKupang.Infrastructure.Database;

#nullable disable

namespace SIGHotelKupang.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241120010740_TambahRatingDiHotel")]
    partial class TambahRatingDiHotel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FasilitasHotel", b =>
                {
                    b.Property<int>("DaftarFasilitasId")
                        .HasColumnType("integer");

                    b.Property<int>("DaftarHotelId")
                        .HasColumnType("integer");

                    b.HasKey("DaftarFasilitasId", "DaftarHotelId");

                    b.HasIndex("DaftarHotelId");

                    b.ToTable("FasilitasHotel");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.Alamat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Jalan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kelurahan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KodePos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblAlamat");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.Fasilitas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblFasilitas");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.HargaKamarHotel", b =>
                {
                    b.Property<int>("IdHotel")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipeKamar")
                        .HasColumnType("integer");

                    b.Property<double>("HargaKamar")
                        .HasColumnType("double precision");

                    b.HasKey("IdHotel", "IdTipeKamar");

                    b.HasIndex("IdTipeKamar");

                    b.ToTable("TblHargaKamarHotel");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatasAtasJamCheckIn")
                        .HasColumnType("integer");

                    b.Property<int?>("BatasAtasJamCheckOut")
                        .HasColumnType("integer");

                    b.Property<int?>("BatasBawahJamCheckIn")
                        .HasColumnType("integer");

                    b.Property<int?>("BatasBawahJamCheckOut")
                        .HasColumnType("integer");

                    b.Property<string>("FotoHotel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JumlahKamar")
                        .HasColumnType("integer");

                    b.Property<int>("KlasifikasiHotel")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorTelepon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<Point>("TitikKoordinat")
                        .IsRequired()
                        .HasColumnType("geography (point)");

                    b.HasKey("Id");

                    b.ToTable("TblHotel");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.LokasiPenting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KategoriLokasiPenting")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("TitikKoordinat")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.ToTable("TblLokasiPenting");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.TipeKamar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblTipeKamar");
                });

            modelBuilder.Entity("FasilitasHotel", b =>
                {
                    b.HasOne("SIGHotelKupang.Domain.Entities.Fasilitas", null)
                        .WithMany()
                        .HasForeignKey("DaftarFasilitasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGHotelKupang.Domain.Entities.Hotel", null)
                        .WithMany()
                        .HasForeignKey("DaftarHotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.Alamat", b =>
                {
                    b.HasOne("SIGHotelKupang.Domain.Entities.Hotel", "Hotel")
                        .WithOne("Alamat")
                        .HasForeignKey("SIGHotelKupang.Domain.Entities.Alamat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.HargaKamarHotel", b =>
                {
                    b.HasOne("SIGHotelKupang.Domain.Entities.Hotel", "Hotel")
                        .WithMany("DaftarHargaKamarHotel")
                        .HasForeignKey("IdHotel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGHotelKupang.Domain.Entities.TipeKamar", "TipeKamar")
                        .WithMany("DaftarHargaKamarHotel")
                        .HasForeignKey("IdTipeKamar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("TipeKamar");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("Alamat")
                        .IsRequired();

                    b.Navigation("DaftarHargaKamarHotel");
                });

            modelBuilder.Entity("SIGHotelKupang.Domain.Entities.TipeKamar", b =>
                {
                    b.Navigation("DaftarHargaKamarHotel");
                });
#pragma warning restore 612, 618
        }
    }
}
